- name: Setup Development Environment
  hosts: tag__Name_web_app_instance
  become: true
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install pip3
      apt:
        name: python3-pip
        state: present

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Install development tools
      apt:
        name: ["git", "vim", "htop", "curl", "wget"]
        state: present
